In [1]:
import numpy as np

In [6]:
list_1 = [1, 3, 2]
list_2 = [5, 2 ,7, 6, 1, 2]
list_3 = [0, 9]
adj_list = [list_1, list_2, list_3]
print('The adjacency list:\n', adj_list)
print('Graph form:')
for list in adj_list:
    print(list)

The adjacency list:
 [[1, 3, 2], [5, 2, 7, 6, 1, 2], [0, 9]]
Graph form:
[1, 3, 2]
[5, 2, 7, 6, 1, 2]
[0, 9]


In [7]:
adj_matrix = np.arange(16).reshape(4, 4)
print('The adjacency matrix:\n', adj_matrix)

The adjacency matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
G = np.random.randint(0, 20, size=(4, 4))
G

array([[ 1, 12,  1, 12],
       [ 8,  8, 14, 10],
       [ 8,  7, 10, 17],
       [ 9, 16, 13,  7]])

In [26]:
def BFS(graph, vertex):
    # Ready
    unvisited_vertices = [True]*len(graph[0])
    queue = []
    sequence = []

    # Start
    unvisited_vertices[vertex] = False
    queue.append(vertex)

    while len(queue) != 0:
        root = queue[0]
        queue.pop(0)
        sequence.append(root)

        for i in range(len(graph[vertex])):
            # Scan the adjacency vertex, the vertex must be unvisited.
            if i != root and unvisited_vertices[i] == True and graph[root][i] != 0:
                unvisited_vertices[i] = False
                queue.append(i)

    print(sequence)


BFS(G, 3)

[3, 0, 1, 2]


In [37]:
from collections import defaultdict
 
class Graph:

    def __init__(self, graph):

        self.graph = graph

    def DFSUtil(self, v, visited):
        visited.add(v)
        print(v, end=' ')
 
        for neighbour in range(len(self.graph[v])):
            if neighbour not in visited:
                self.DFSUtil(neighbour, visited)
 
    def DFS(self, v):
        visited = set()
        self.DFSUtil(v, visited)

    def display(self):
        print(self.graph)

graph = Graph(G)
graph.DFS(2)
# graph.display()

2 0 1 3 